bcgov/platform-services-registry-api

- src/graphql/resolvers/Users.test.js
> Tests for user resolvers #698

- src/graphql/resolvers/Requests.test.js
Tests for request resolvers. Looks like there's a merge conflict I need to clean up.
> fleshed out requests for more coverage

- prisma/schema.prisma
- schema.graphql
- src/__generated__/resolvers-types.ts
- src/ches/emailHandlers.ts
- src/nats/constants.ts
ministry names list updated according to provided one https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries
ministry names are also replaced with human friendly in emails
> ministries list updated, converted to human friendly names for emails

- src/ches/emailHandlers.ts
fixed showing quota before changing in confirmation emails for edit quota request
> updated quota in confirmation email

- src/ches/emailHandlers.ts
- src/controllers/provisionerCallbackHandler.ts
- src/nats/constants.ts
- src/resolvers/mutations/privateCloudRequestDecision.ts
edit and create product emails are sent after provisioning
> Email after provisioning

- src/resolvers/mutations/privateCloudEditRequest.ts
- src/resolvers/queries/projects.ts
case insensitive search implemented for name, users' names, description
> case insensitive search implemented

- src/resolvers/queries/projects.ts
filtering with cluster and ministry renewed
> added ministry/cluster filtering

- src/ches/emailHandlers.ts
- src/resolvers/mutations/privateCloudEditRequest.ts
added additional check before sending quota has been changed email.
> sending quota change emails after only contact change canceled

- src/resolvers/queries/projects.ts
search with First and last name in search field
> search with first and last name

- schema.graphql
- src/__generated__/resolvers-types.ts
- src/ches/new-templates/product-contact-change-confirmation-email.html
- src/resolvers/queries/projects.ts
added search filtering and sort(by name) functionality for regular user products. Changed wording for contacts update
> Seach filter functionality user

- src/ches/emailHandlers.ts
- src/ches/new-templates/product-quota-change-techleads-email.html
- src/resolvers/queries/projects.ts
emails for teachleads after quota change approval
> Email tech leads tips

- package-lock.json
- package.json
- src/index.ts
- src/nats/message.ts
- src/nats/sendNatsMessage.ts
- src/resolvers/mutations/privateCloudEditRequest.ts
- src/resolvers/mutations/privateCloudReProvisionProject.ts
- src/resolvers/mutations/privateCloudReProvisionRequest.ts
- src/resolvers/mutations/privateCloudRequestDecision.ts
added licencePlate and workflow fields to natsMessage  added node-cron module for cron job
licencePlate: licencePlate,
workflow: `${Cluster[cluster]}-${licencePlate}-${requestId}`
> added licencePlate and workflow fields to natsMessage

- package-lock.json
- package.json
- src/index.ts
- src/nats/message.ts
- src/nats/sendNatsMessage.ts
- src/resolvers/mutations/privateCloudEditRequest.ts
- src/resolvers/mutations/privateCloudReProvisionProject.ts
- src/resolvers/mutations/privateCloudReProvisionRequest.ts
- src/resolvers/mutations/privateCloudRequestDecision.ts
Reverts bcgov/platform-services-registry-api#55
> Revert "added licencePlate and workflow fields to natsMessage"

- package-lock.json
- package.json
- src/index.ts
- src/nats/message.ts
- src/nats/sendNatsMessage.ts
- src/resolvers/mutations/privateCloudEditRequest.ts
- src/resolvers/mutations/privateCloudReProvisionProject.ts
- src/resolvers/mutations/privateCloudReProvisionRequest.ts
- src/resolvers/mutations/privateCloudRequestDecision.ts
Reverts bcgov/platform-services-registry-api#56
> Revert "Revert "added licencePlate and workflow fields to natsMessage""

- README.md
- prisma/schema.prisma
- schema.graphql
- src/__generated__/resolvers-types.ts
- src/natsPubSub/publicCloud/message.ts
- src/resolvers/mutations/publicCloud/createRequest.ts
- src/resolvers/mutations/publicCloud/editRequest.ts
added account coding component to create and  edit product public cloud pages 
to public cloud request page
> account coding added to model and nats message

- src/controllers/getRequestStatus.ts
added conditions to cron-job logs
Completed with error (failed)
completed: true
phase: Error - we have a problem
Completed successfully
completed: true
phase: Succeeded - completed
In progress
completed: null
phase: Running - in progress
> added conditions to cron-job logs

- src/resolvers/user.ts
Fixed the query that returns weather a user has an existing project
> fixed new user query

- src/ches/emailHandlersPrivate.ts
- src/ches/emailHelpers.ts
- src/ches/privateEmailTemplates/quota-and-tlpo-changes.html
- src/ches/privateEmailTemplates/quota-request-completion-email.html
- src/ches/privateEmailTemplates/quota-request-received-email.html
- src/ches/privateEmailTemplates/request-denial-email.html
- src/ches/privateEmailTemplates/super-admin-request-email.html
- src/ches/publicEmailTemplates/edit-request-received.html
- src/controllers/getIdirEmails.ts
fixed tool namespace storage in private cloud emails, and change contact public cloud emails, added filter for search users =userType eq "Member"
> hot fixies and query url changed

- prisma/schema.prisma
- schema.graphql
- src/__generated__/resolvers-types.ts
decimal input for public cloud budget
> decimal input for budget

- schema.graphql
- src/__generated__/resolvers-types.ts
- src/natsPubSub/index.ts
- src/natsPubSub/publicCloud/message.ts
- src/resolvers/user.ts
isNew as Boolean to isNew as an object for private and public project PO/TL, .emal instead of !== undefined or null, as Boolean for public nutsmessage
> Is new public and private 1000

- prisma/schema.prisma
- schema.graphql
- src/__generated__/resolvers-types.ts
- src/resolvers/mutations/index.ts
- src/resolvers/mutations/publicCloud/deleteRequest.ts
- src/resolvers/queries/publicCloud/projects.ts
deletion feature for public cloud and nats message
> Public deletion 906

- src/mautic/index.js
- src/resolvers/mutations/privateCloud/editRequest.ts
- src/resolvers/mutations/privateCloud/requestDecision.ts
- src/resolvers/mutations/publicCloud/editRequest.ts
- src/resolvers/mutations/publicCloud/requestDecision.ts
removed segmentName
added clusterName
added platformName
added FirstNAme
added LastName
added email
changed api link - https://mautic-subscription-api-prod-de0974-prod.apps.silver.devops.gov.bc.ca/segments/contact/cluster/add
> mautic updated query

- package-lock.json
- package.json
- src/ches/emailHandlersPrivate.ts
- src/ches/emailHandlersPublic.ts
- src/ches/emailHelpers.ts
- src/resolvers/mutations/publicCloud/editRequest.ts
added condition to send emails only in cases of account coding, budget or PO/TO changes
> Public name change bug 1004

- src/ches/privateEmailTemplates/provisioning-request-completion-email.html
> updated email links
